[package]
name = "mandel-dev"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.2"
crossbeam = "0.8.2"
eframe = "0.18.0"
nalgebra = "0.31.1"
png = "0.17.5"
rayon = "1.5.3"
